apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus-app
  labels:
    app: docusaurus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
      - name: docusaurus
        image: docusaurus-example:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docusaurus-service
  labels:
    app: docusaurus
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
  selector:
    app: docusaurus