name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  IMAGE_NAME: docusaurus-example
  # WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    
    outputs:
      image-tag: ${{ steps.tag.outputs.tag }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/setup-buildx-action@v3
    
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Set image tag
      id: tag
      run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
    
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  # deploy:
  #   name: Deploy to Azure
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   steps:
  #   - uses: azure/webapps-deploy@v3
  #     with:
  #       app-name: ${{ env.WEBAPP_NAME }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image-tag }}
